### PR TITLE
server.py update

### PR DESCRIPTION
**Pull request by james-doe**
New method inserted in Server.py, the method change the Server instance for specific purposes

### CODE REVIEW

**Comment by MatteoBosco89** [comment]
The method is not useful and not required. In addition the method is not well formed, in fact is plenty of magic numbers and hardcoded strings.

**Comment by SenselessMite** [comment]
The method inconsistenMethod added in Server.py doesn't add any new necessary function so it is useless to add it

**Comment by augusto196** [comment]
this method is not good otherwise you have to change the code

**Review by augusto196 — COMMENTED** [review]
this method is not good otherwise you have to change the code

**Comment by MatteoBosco89** [comment]
discarded

**Review by SenselessMite — COMMENTED** [review]
The method doesn't add any new feature

**Pull request closed without merging**
